In [1]:
import pandas as pandas
import geopandas as gpd
import numpy as np
import shapely

In [2]:
ind_vil = gpd.read_file(r"D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\Maps\BM_India-village.geojson")
ind_vil

,objectid,vilnam_soi,dtname,stname,stcode11,dtcode11,sdtcode11,vilcode11,sdtname,vilname11,...,gp_name,subdt_lgd,block_name,block_lgd,remark,ac_no,test,st_area(shape),st_length(shape),geometry
0,1,MUD,Nicobars,ANDAMAN & NICOBAR,35,638,05917,645088,Nancowry,Mus*,...,Mus,5917,NANCOWRIE,6500,None,NaN,NaN,1.822050e+07,42929.614809,"MULTIPOLYGON (((10416804.839 906920.367, 10416..."
1,2,CAMORTA,Nicobars,ANDAMAN & NICOBAR,35,638,05917,645122,Nancowry,Knot,...,Knot,5917,NANCOWRIE,6500,None,NaN,NaN,1.425489e+08,141986.587845,"MULTIPOLYGON (((10409792.403 919908.005, 10409..."
2,3,,Nicobars,ANDAMAN & NICOBAR,35,638,05917,,Nancowry,,...,,5917,NANCOWRIE,6500,None,NaN,NaN,9.713589e+03,356.900385,"MULTIPOLYGON (((10409887.786 901863.188, 10409..."
3,4,,Nicobars,ANDAMAN & NICOBAR,35,638,05917,,Nancowry,,...,,5917,NANCOWRIE,6500,None,NaN,NaN,2.595946e+03,188.312520,"MULTIPOLYGON (((10410025.828 901213.052, 10410..."
4,5,,Nicobars,ANDAMAN & NICOBAR,35,638,05917,,Nancowry,,...,,5917,NANCOWRIE,6500,None,NaN,NaN,2.993515e+03,199.500643,"MULTIPOLYGON (((10409931.527 900704.180, 10409..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
584610,584609,DHAKORAN KHURD,S.A.S Nagar,PUNJAB,03,052,00266,039087,Kharar,Dhakoran Kalan (154),...,DHAKORAN KALAN,266,MAJRI,335,None,NaN,NaN,1.961102e+06,6164.435474,"MULTIPOLYGON (((8535853.965 3610090.381, 85359..."
584611,584612,RESERVED FOREST,Khairgarh Chhuikhadan Gandai,CHHATTISGARH,22,821,0,440093,Gandai,Thakurtola,...,THAKURTOLA,7264,CHHUIKHADAN,3709,None,73.0,584613.0,7.902507e+07,96080.588898,"MULTIPOLYGON (((9017777.917 2467958.981, 90172..."
584612,584613,RESERVED FOREST,Manendragarh Chirimiri Bharatpur,CHHATTISGARH,22,822,03234,,Manendragarh,,...,,3234,MANENDRAGARH,3677,None,2.0,584614.0,1.595390e+08,153174.460763,"MULTIPOLYGON (((9159039.668 2668628.787, 91617..."
584613,584614,RESERVED FOREST,Manendragarh Chirimiri Bharatpur,CHHATTISGARH,22,822,03231,,Bharatpur,,...,,3231,BHARATPUR,3675,None,1.0,584615.0,7.451271e+08,604984.409538,"MULTIPOLYGON (((9116430.065 2709052.394, 91158..."
584614,584615,BAGMALA PF,Sarangarh Bilaigarh,CHHATTISGARH,22,825,03329,,Bilaigarh,,...,,3329,BILAIGARH,3697,None,43.0,584616.0,6.325967e+07,126649.269226,"MULTIPOLYGON (((9212455.548 2462356.036, 92113..."

In [3]:
print(ind_vil.crs)

EPSG:3857

In [3]:
od = ind_vil.loc[ind_vil['stname'] == 'ODISHA']
od

,objectid,vilnam_soi,dtname,stname,stcode11,dtcode11,sdtcode11,vilcode11,sdtname,vilname11,...,gp_name,subdt_lgd,block_name,block_lgd,remark,ac_no,test,st_area(shape),st_length(shape),geometry
284616,288201,JAMUNDA,Anugul,ODISHA,21,384,03021,405256,Bantala,Jamunda,...,GADATARASHA,3021,ANUGUL,3276,None,61.0,NaN,2.049085e+06,7073.491671,"MULTIPOLYGON (((9470983.793 2357052.769, 94709..."
284633,304006,LOHARADHIHA,Gajapati,ODISHA,21,389,03102,414035,R.Udayagiri,Loharadhiha,...,,3102,R.UDAYAGIRI,3362,None,136.0,NaN,5.151173e+04,843.729389,"MULTIPOLYGON (((9396677.178 2189398.056, 93967..."
284661,288433,RANKASINGA,Anugul,ODISHA,21,384,03010,404172,Banarpal,Rankasinga,...,,3010,BANARPAL,3278,None,61.0,NaN,1.568123e+06,5445.011989,"MULTIPOLYGON (((9482884.119 2362718.900, 94830..."
284698,288434,JUHARAPUR,Anugul,ODISHA,21,384,03010,404173,Banarpal,Juharpur,...,BAULIGARH,3010,BANARPAL,3278,None,61.0,NaN,6.597870e+05,3720.593205,"MULTIPOLYGON (((9485406.545 2362434.097, 94855..."
284703,288435,LACHHABANDH,Anugul,ODISHA,21,384,03021,405226,Bantala,Lachhabandha,...,DHOKUTA,3021,ANUGUL,3276,None,61.0,NaN,6.973392e+05,3750.306099,"MULTIPOLYGON (((9466510.309 2362502.284, 94668..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340886,340840,FOREST,Kandhamal,ODISHA,21,390,03114,,G.Udayagiri,,...,,3114,G.UDAYAGIRI,3425,None,83.0,NaN,2.323739e+06,6667.827184,"MULTIPOLYGON (((9396944.390 2302499.861, 93968..."
340887,340841,FOREST,Kandhamal,ODISHA,21,390,03110,,Gochhapada,,...,,3110,PHIRINGIA,3429,None,84.0,NaN,6.469838e+06,22834.048437,"MULTIPOLYGON (((9357561.045 2323826.587, 93574..."
340888,340842,MATKHAI RESERVED FOREST,Balangir,ODISHA,21,393,03142,,Balangir,,...,,3142,PUINTALA,3294,None,68.0,NaN,4.785256e+06,16980.847517,"MULTIPOLYGON (((9297832.236 2345131.312, 92978..."
340889,340844,TALCHER BORDER R F,Dhenkanal,ODISHA,21,383,02987,,Parajang,,...,,2987,KANKADA HAD,3354,None,58.0,NaN,2.232779e+06,9667.405961,"MULTIPOLYGON (((9488673.837 2398922.318, 94885..."
340890,340845,FOREST,Sundargarh,ODISHA,21,374,02823,,Lathikata,,...,,2823,LATHIKATA,3583,None,11.0,NaN,4.026908e+07,75686.373718,"MULTIPOLYGON (((9458219.206 2532158.117, 94583..."

In [4]:
od['block_lgd'].nunique()

314

#### Create od_vil.csv

In [7]:
od_vil = od.loc[od['vilcode11']!=""]
od_vil

,objectid,vilnam_soi,dtname,stname,stcode11,dtcode11,sdtcode11,vilcode11,sdtname,vilname11,...,gp_name,subdt_lgd,block_name,block_lgd,remark,ac_no,test,st_area(shape),st_length(shape),geometry
284616,288201,JAMUNDA,Anugul,ODISHA,21,384,03021,405256,Bantala,Jamunda,...,GADATARASHA,3021,ANUGUL,3276,None,61.0,NaN,2.049085e+06,7073.491671,"MULTIPOLYGON (((9470983.793 2357052.769, 94709..."
284633,304006,LOHARADHIHA,Gajapati,ODISHA,21,389,03102,414035,R.Udayagiri,Loharadhiha,...,,3102,R.UDAYAGIRI,3362,None,136.0,NaN,5.151173e+04,843.729389,"MULTIPOLYGON (((9396677.178 2189398.056, 93967..."
284661,288433,RANKASINGA,Anugul,ODISHA,21,384,03010,404172,Banarpal,Rankasinga,...,,3010,BANARPAL,3278,None,61.0,NaN,1.568123e+06,5445.011989,"MULTIPOLYGON (((9482884.119 2362718.900, 94830..."
284698,288434,JUHARAPUR,Anugul,ODISHA,21,384,03010,404173,Banarpal,Juharpur,...,BAULIGARH,3010,BANARPAL,3278,None,61.0,NaN,6.597870e+05,3720.593205,"MULTIPOLYGON (((9485406.545 2362434.097, 94855..."
284703,288435,LACHHABANDH,Anugul,ODISHA,21,384,03021,405226,Bantala,Lachhabandha,...,DHOKUTA,3021,ANUGUL,3276,None,61.0,NaN,6.973392e+05,3750.306099,"MULTIPOLYGON (((9466510.309 2362502.284, 94668..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340823,340784,RATU>N,Kendujhar,ODISHA,21,375,02854,387018,Anandapur,Ratuan,...,KODAPADA,2854,ANANDAPUR,3443,None,22.0,NaN,1.120183e+08,120179.866772,"MULTIPOLYGON (((9575154.387 2455197.102, 95749..."
340838,340803,RAURAKELA TOWN,Sundargarh,ODISHA,21,374,02833,801819,Raurkela (ITS)P.S.,ROURKELA (M+OG),...,,2833,BISRA,3575,None,12.0,NaN,5.076761e+07,33827.064663,"MULTIPOLYGON (((9446261.488 2544287.365, 94465..."
340869,340824,KULSRA,Deogarh,ODISHA,21,373,02801,382903,Barkot,Kukeimuhan,...,BALANDA,2801,BARKOTE,3346,None,19.0,NaN,4.176172e+07,58276.628175,"MULTIPOLYGON (((9461957.678 2455432.767, 94620..."
340870,340825,KULSRA,Deogarh,ODISHA,21,373,02801,382903,Barkot,Kukeimuhan,...,BALANDA,2801,BARKOTE,3346,None,19.0,NaN,2.587619e+06,9259.143085,"MULTIPOLYGON (((9461345.701 2441346.843, 94613..."
340871,340826,KULSRA,Deogarh,ODISHA,21,373,02800,382675,Debagarh,Chingudijharan,...,JHARAGOGUA,2800,BARKOTE,3346,None,19.0,NaN,2.828620e+07,33265.589953,"MULTIPOLYGON (((9435554.347 2457338.995, 94347..."

In [10]:
od_vil = od_vil.drop_duplicates(subset='vilcode11', keep='first')
od_vil

,objectid,vilnam_soi,dtname,stname,stcode11,dtcode11,sdtcode11,vilcode11,sdtname,vilname11,...,gp_name,subdt_lgd,block_name,block_lgd,remark,ac_no,test,st_area(shape),st_length(shape),geometry
284616,288201,JAMUNDA,Anugul,ODISHA,21,384,03021,405256,Bantala,Jamunda,...,GADATARASHA,3021,ANUGUL,3276,None,61.0,NaN,2.049085e+06,7073.491671,"MULTIPOLYGON (((9470983.793 2357052.769, 94709..."
284633,304006,LOHARADHIHA,Gajapati,ODISHA,21,389,03102,414035,R.Udayagiri,Loharadhiha,...,,3102,R.UDAYAGIRI,3362,None,136.0,NaN,5.151173e+04,843.729389,"MULTIPOLYGON (((9396677.178 2189398.056, 93967..."
284661,288433,RANKASINGA,Anugul,ODISHA,21,384,03010,404172,Banarpal,Rankasinga,...,,3010,BANARPAL,3278,None,61.0,NaN,1.568123e+06,5445.011989,"MULTIPOLYGON (((9482884.119 2362718.900, 94830..."
284698,288434,JUHARAPUR,Anugul,ODISHA,21,384,03010,404173,Banarpal,Juharpur,...,BAULIGARH,3010,BANARPAL,3278,None,61.0,NaN,6.597870e+05,3720.593205,"MULTIPOLYGON (((9485406.545 2362434.097, 94855..."
284703,288435,LACHHABANDH,Anugul,ODISHA,21,384,03021,405226,Bantala,Lachhabandha,...,DHOKUTA,3021,ANUGUL,3276,None,61.0,NaN,6.973392e+05,3750.306099,"MULTIPOLYGON (((9466510.309 2362502.284, 94668..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
340704,340691,DHANGIRBUDI,Sundargarh,ODISHA,21,374,02805,383944,Lephripara,Dhangergudi,...,GUNDIADIHI,2805,BALISANKARA,3573,None,8.0,NaN,7.641719e+06,11091.084432,"MULTIPOLYGON (((9325593.941 2542266.283, 93259..."
340705,340692,MANAHARPUR,Sundargarh,ODISHA,21,374,02805,383628,Lephripara,Manoharpur,...,SARAFGARH,2805,LEPHRIPARA,3584,None,8.0,NaN,4.194750e+06,8337.488363,"MULTIPOLYGON (((9315041.819 2537450.416, 93148..."
340706,340693,GAIKANPALI,Sundargarh,ODISHA,21,374,02804,383496,Hemgir,Gaikanpali,...,TOPRIA,2804,HEMGIR,3578,None,9.0,NaN,5.792245e+06,11148.707710,"MULTIPOLYGON (((9301755.976 2518042.522, 93017..."
340707,340694,DHUBENDAND,Sundargarh,ODISHA,21,374,02810,383956,Kinjirkela,Dhubendand,...,DHUBENDAND,2810,BALISANKARA,3573,None,8.0,NaN,4.513921e+06,8960.875402,"MULTIPOLYGON (((9341596.510 2542133.011, 93417..."
340708,340695,,Sundargarh,ODISHA,21,374,02813,384176,Kutra,Tunmura,...,TUNMURA,2813,KUTRA,3581,None,13.0,NaN,1.384335e+07,17919.337289,"MULTIPOLYGON (((9405081.386 2538125.516, 94051..."

In [12]:
od_vil.to_csv('ODISHA_VILLAGES_shapes.csv')

In [15]:
od_vil_reduced = od_vil.drop(['geometry','remark','ac_no','test','st_area(shape)','st_length(shape)','vil_lgd','dist_lgd','state_lgd'],axis=1)
od_vil_reduced.to_csv('ODISHA_VILLAGES_MASTER.csv')

### Dissolve village boundaries to blocks

Columns required: block_name, block_lgd, geometry, subdistrict, dtname

In [6]:

# Select only the necessary columns
od_block = od[['dtname', 'dtcode11', 'block_name', 'block_lgd','geometry']]

# Dissolve based on the block column to merge village boundaries into blocks
od_block = od_block.dissolve(by='block_lgd', as_index=False)

In [7]:
od_block.to_file('odisha_block.geojson')