In [1]:
import geopandas as gpd
import numpy as np
import pandas as pd
import geojson_validator

In [26]:
gdf = gpd.read_file(r"D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\IDS-DRR-Assam\Maps\Assam_Revenue_Circles\assam_revenue_circle_nov2022.geojson")

fixed_geo = geojson_validator.fix_geometries(gdf)#, optional=["duplicate_nodes"])


geo_fixed = pd.DataFrame.from_dict(fixed_geo)
geo_fixed

2024-10-05_00:54:23.760 | Criteria 'optional': ['duplicate_nodes']
2024-10-05_00:54:23.761 | Criteria 'invalid': ['unclosed', 'exterior_not_ccw', 'interior_not_cw']
2024-10-05_00:54:23.762 | Criteria 'problematic': ['duplicate_nodes']
2024-10-05_00:54:24.243 | Validation results: {'invalid': {'exterior_not_ccw': [{0: [0]}, {1: [0]}, {2: [0]}, {3: [0]}, {4: [0]}, {5: [0]}, {6: [0]}, {7: [0]}, {8: [0]}, {9: [0]}, {10: [0]}, {11: [0]}, {12: [0]}, {13: [0]}, {14: [0]}, {15: [0]}, {16: [0]}, {17: [0]}, {18: [0]}, {19: [0]}, {20: [0]}, {21: [0]}, {22: [0]}, {23: [0]}, {24: [0]}, {25: [0]}, {26: [0]}, {27: [0]}, {28: [0]}, {29: [0]}, {30: [0]}, {31: [0]}, {32: [0]}, {33: [0]}, {34: [0]}, {35: [0]}, {36: [0]}, {37: [0]}, {38: [0]}, {39: [0]}, {40: [0]}, {41: [0]}, {42: [0]}, {43: [0]}, {44: [0]}, {45: [0]}, {46: [0]}, {47: [0]}, {48: [0]}, {49: [0]}, {50: [0]}, {51: [0]}, {52: [0]}, {53: [0]}, {54: [0]}, {55: [0]}, {56: [0]}, {57: [0]}, {58: [0]}, {59: [0]}, {60: [0]}, {61: [0]}, {62: [0]}, {63: [0]}, {64: [0]}, {65: [0]}, {66: [0]}, {67: [0]}, {68: [0]}, {69: [0]}, {70: [0]}, {71: [0]}, {72: [0]}, {73: [0]}, {74: [0]}, {75: [0]}, {76: [0]}, {77: [0]}, {78: [0]}, {79: [0]}, {80: [0]}, {81: [0]}, {82: [0]}, {83: [0]}, {84: [0]}, {85: [0]}, {86: [0]}, {87: [0]}, {88: [0]}, {89: [0]}, {90: [0]}, {91: [0]}, {92: [0]}, {93: [0]}, {94: [0]}, {95: [0]}, {96: [0]}, {97: [0]}, {98: [0]}, {99: [0]}, {100: [0]}, {101: [0]}, {102: [0]}, {103: [0]}, {104: [0]}, {105: [0]}, {106: [0]}, {107: [0]}, {108: [0]}, {109: [0]}, {110: [0]}, {111: [0]}, {112: [0]}, {113: [0]}, {114: [0]}, {115: [0]}, {116: [0]}, {117: [0]}, {118: [0]}, {119: [0]}, {120: [0]}, {121: [0]}, {122: [0]}, {123: [0]}, {124: [0]}, {125: [0]}, {126: [0]}, {127: [0]}, {128: [0]}, {129: [0]}, {130: [0]}, {131: [0]}, {132: [0]}, {133: [0]}, {134: [0]}, {135: [0]}, {136: [0]}, {137: [0]}, {138: [0]}, {139: [0]}, {140: [0]}, {141: [0]}, {142: [0]}, {143: [0]}, {144: [0]}, {145: [0]}, {146: [0]}, {147: [0]}, {148: [0]}, {149: [0]}, {150: [0]}, {151: [0]}, {152: [0]}, {153: [0]}, {154: [0]}, {155: [0]}, {156: [0]}, {157: [0]}, {158: [0]}, {159: [0]}, {160: [0]}, {161: [0]}, {162: [0]}, {163: [0]}, {164: [0]}, {165: [0]}, {166: [0]}, {167: [0]}, {168: [0]}, {169: [0]}, {170: [0]}, {171: [0]}, {172: [0]}, {173: [0]}, {174: [0]}, {175: [0]}, {176: [0]}, {177: [0, 1, 2, 3, 4, 5]}, {178: [0]}, {179: [0]}], 'interior_not_cw': [{178: [0]}]}, 'problematic': {}, 'count_geometry_types': {'MultiPolygon': 180}, 'skipped_validation': []}
2024-10-05_00:54:24.433 | Structure validation results: {"Array is not deep enough nested, expected depth 4 for type 'MultiPolygon', found depth 1": {'path': ['/features/0/geometry/coordinates', '/features/1/geometry/coordinates', '/features/2/geometry/coordinates', '/features/3/geometry/coordinates', '/features/4/geometry/coordinates', '/features/5/geometry/coordinates', '/features/6/geometry/coordinates', '/features/7/geometry/coordinates', '/features/8/geometry/coordinates', '/features/9/geometry/coordinates', '/features/10/geometry/coordinates', '/features/11/geometry/coordinates', '/features/12/geometry/coordinates', '/features/13/geometry/coordinates', '/features/14/geometry/coordinates', '/features/15/geometry/coordinates', '/features/16/geometry/coordinates', '/features/17/geometry/coordinates', '/features/18/geometry/coordinates', '/features/19/geometry/coordinates', '/features/20/geometry/coordinates', '/features/21/geometry/coordinates', '/features/22/geometry/coordinates', '/features/23/geometry/coordinates', '/features/24/geometry/coordinates', '/features/25/geometry/coordinates', '/features/26/geometry/coordinates', '/features/27/geometry/coordinates', '/features/28/geometry/coordinates', '/features/29/geometry/coordinates', '/features/30/geometry/coordinates', '/features/31/geometry/coordinates', '/features/32/geometry/coordinates', '/features/33/geometry/coordinates', '/features/34/geometry/coordinates', '/features/35/geometry/coordinates', '/features/36/geometry/coordinates', '/features/37/geometry/coordinates', '/features/38/geometry/coordinates', '/features/39/geometry/coordinates', '/features/40/geometry/coordinates', '/features/41/geometry/coordinates', '/features/42/geometry/coordinates', '/features/43/geometry/coordinates', '/features/44/geometry/coordinates', '/features/45/geometry/coordinates', '/features/46/geometry/coordinates', '/features/47/geometry/coordinates', '/features/48/geometry/coordinates', '/features/49/geometry/coordinates', '/features/50/geometry/coordinates', '/features/51/geometry/coordinates', '/features/52/geometry/coordinates', '/features/53/geometry/coordinates', '/features/54/geometry/coordinates', '/features/55/geometry/coordinates', '/features/56/geometry/coordinates', '/features/57/geometry/coordinates', '/features/58/geometry/coordinates', '/features/59/geometry/coordinates', '/features/60/geometry/coordinates', '/features/61/geometry/coordinates', '/features/62/geometry/coordinates', '/features/63/geometry/coordinates', '/features/64/geometry/coordinates', '/features/65/geometry/coordinates', '/features/66/geometry/coordinates', '/features/67/geometry/coordinates', '/features/68/geometry/coordinates', '/features/69/geometry/coordinates', '/features/70/geometry/coordinates', '/features/71/geometry/coordinates', '/features/72/geometry/coordinates', '/features/73/geometry/coordinates', '/features/74/geometry/coordinates', '/features/75/geometry/coordinates', '/features/76/geometry/coordinates', '/features/77/geometry/coordinates', '/features/78/geometry/coordinates', '/features/79/geometry/coordinates', '/features/80/geometry/coordinates', '/features/81/geometry/coordinates', '/features/82/geometry/coordinates', '/features/83/geometry/coordinates', '/features/84/geometry/coordinates', '/features/85/geometry/coordinates', '/features/86/geometry/coordinates', '/features/87/geometry/coordinates', '/features/88/geometry/coordinates', '/features/89/geometry/coordinates', '/features/90/geometry/coordinates', '/features/91/geometry/coordinates', '/features/92/geometry/coordinates', '/features/93/geometry/coordinates', '/features/94/geometry/coordinates', '/features/95/geometry/coordinates', '/features/96/geometry/coordinates', '/features/97/geometry/coordinates', '/features/98/geometry/coordinates', '/features/99/geometry/coordinates', '/features/100/geometry/coordinates', '/features/101/geometry/coordinates', '/features/102/geometry/coordinates', '/features/103/geometry/coordinates', '/features/104/geometry/coordinates', '/features/105/geometry/coordinates', '/features/106/geometry/coordinates', '/features/107/geometry/coordinates', '/features/108/geometry/coordinates', '/features/109/geometry/coordinates', '/features/110/geometry/coordinates', '/features/111/geometry/coordinates', '/features/112/geometry/coordinates', '/features/113/geometry/coordinates', '/features/114/geometry/coordinates', '/features/115/geometry/coordinates', '/features/116/geometry/coordinates', '/features/117/geometry/coordinates', '/features/118/geometry/coordinates', '/features/119/geometry/coordinates', '/features/120/geometry/coordinates', '/features/121/geometry/coordinates', '/features/122/geometry/coordinates', '/features/123/geometry/coordinates', '/features/124/geometry/coordinates', '/features/125/geometry/coordinates', '/features/126/geometry/coordinates', '/features/127/geometry/coordinates', '/features/128/geometry/coordinates', '/features/129/geometry/coordinates', '/features/130/geometry/coordinates', '/features/131/geometry/coordinates', '/features/132/geometry/coordinates', '/features/133/geometry/coordinates', '/features/134/geometry/coordinates', '/features/135/geometry/coordinates', '/features/136/geometry/coordinates', '/features/137/geometry/coordinates', '/features/138/geometry/coordinates', '/features/139/geometry/coordinates', '/features/140/geometry/coordinates', '/features/141/geometry/coordinates', '/features/142/geometry/coordinates', '/features/143/geometry/coordinates', '/features/144/geometry/coordinates', '/features/145/geometry/coordinates', '/features/146/geometry/coordinates', '/features/147/geometry/coordinates', '/features/148/geometry/coordinates', '/features/149/geometry/coordinates', '/features/150/geometry/coordinates', '/features/151/geometry/coordinates', '/features/152/geometry/coordinates', '/features/153/geometry/coordinates', '/features/154/geometry/coordinates', '/features/155/geometry/coordinates', '/features/156/geometry/coordinates', '/features/157/geometry/coordinates', '/features/158/geometry/coordinates', '/features/159/geometry/coordinates', '/features/160/geometry/coordinates', '/features/161/geometry/coordinates', '/features/162/geometry/coordinates', '/features/163/geometry/coordinates', '/features/164/geometry/coordinates', '/features/165/geometry/coordinates', '/features/166/geometry/coordinates', '/features/167/geometry/coordinates', '/features/168/geometry/coordinates', '/features/169/geometry/coordinates', '/features/170/geometry/coordinates', '/features/171/geometry/coordinates', '/features/172/geometry/coordinates', '/features/173/geometry/coordinates', '/features/174/geometry/coordinates', '/features/175/geometry/coordinates', '/features/176/geometry/coordinates', '/features/177/geometry/coordinates', '/features/178/geometry/coordinates', '/features/179/geometry/coordinates'], 'feature': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179]}, "'bbox' member must be a one-dimensional array with bounding box coordinates": {'path': ['/features/0/bbox', '/features/1/bbox', '/features/2/bbox', '/features/3/bbox', '/features/4/bbox', '/features/5/bbox', '/features/6/bbox', '/features/7/bbox', '/features/8/bbox', '/features/9/bbox', '/features/10/bbox', '/features/11/bbox', '/features/12/bbox', '/features/13/bbox', '/features/14/bbox', '/features/15/bbox', '/features/16/bbox', '/features/17/bbox', '/features/18/bbox', '/features/19/bbox', '/features/20/bbox', '/features/21/bbox', '/features/22/bbox', '/features/23/bbox', '/features/24/bbox', '/features/25/bbox', '/features/26/bbox', '/features/27/bbox', '/features/28/bbox', '/features/29/bbox', '/features/30/bbox', '/features/31/bbox', '/features/32/bbox', '/features/33/bbox', '/features/34/bbox', '/features/35/bbox', '/features/36/bbox', '/features/37/bbox', '/features/38/bbox', '/features/39/bbox', '/features/40/bbox', '/features/41/bbox', '/features/42/bbox', '/features/43/bbox', '/features/44/bbox', '/features/45/bbox', '/features/46/bbox', '/features/47/bbox', '/features/48/bbox', '/features/49/bbox', '/features/50/bbox', '/features/51/bbox', '/features/52/bbox', '/features/53/bbox', '/features/54/bbox', '/features/55/bbox', '/features/56/bbox', '/features/57/bbox', '/features/58/bbox', '/features/59/bbox', '/features/60/bbox', '/features/61/bbox', '/features/62/bbox', '/features/63/bbox', '/features/64/bbox', '/features/65/bbox', '/features/66/bbox', '/features/67/bbox', '/features/68/bbox', '/features/69/bbox', '/features/70/bbox', '/features/71/bbox', '/features/72/bbox', '/features/73/bbox', '/features/74/bbox', '/features/75/bbox', '/features/76/bbox', '/features/77/bbox', '/features/78/bbox', '/features/79/bbox', '/features/80/bbox', '/features/81/bbox', '/features/82/bbox', '/features/83/bbox', '/features/84/bbox', '/features/85/bbox', '/features/86/bbox', '/features/87/bbox', '/features/88/bbox', '/features/89/bbox', '/features/90/bbox', '/features/91/bbox', '/features/92/bbox', '/features/93/bbox', '/features/94/bbox', '/features/95/bbox', '/features/96/bbox', '/features/97/bbox', '/features/98/bbox', '/features/99/bbox', '/features/100/bbox', '/features/101/bbox', '/features/102/bbox', '/features/103/bbox', '/features/104/bbox', '/features/105/bbox', '/features/106/bbox', '/features/107/bbox', '/features/108/bbox', '/features/109/bbox', '/features/110/bbox', '/features/111/bbox', '/features/112/bbox', '/features/113/bbox', '/features/114/bbox', '/features/115/bbox', '/features/116/bbox', '/features/117/bbox', '/features/118/bbox', '/features/119/bbox', '/features/120/bbox', '/features/121/bbox', '/features/122/bbox', '/features/123/bbox', '/features/124/bbox', '/features/125/bbox', '/features/126/bbox', '/features/127/bbox', '/features/128/bbox', '/features/129/bbox', '/features/130/bbox', '/features/131/bbox', '/features/132/bbox', '/features/133/bbox', '/features/134/bbox', '/features/135/bbox', '/features/136/bbox', '/features/137/bbox', '/features/138/bbox', '/features/139/bbox', '/features/140/bbox', '/features/141/bbox', '/features/142/bbox', '/features/143/bbox', '/features/144/bbox', '/features/145/bbox', '/features/146/bbox', '/features/147/bbox', '/features/148/bbox', '/features/149/bbox', '/features/150/bbox', '/features/151/bbox', '/features/152/bbox', '/features/153/bbox', '/features/154/bbox', '/features/155/bbox', '/features/156/bbox', '/features/157/bbox', '/features/158/bbox', '/features/159/bbox', '/features/160/bbox', '/features/161/bbox', '/features/162/bbox', '/features/163/bbox', '/features/164/bbox', '/features/165/bbox', '/features/166/bbox', '/features/167/bbox', '/features/168/bbox', '/features/169/bbox', '/features/170/bbox', '/features/171/bbox', '/features/172/bbox', '/features/173/bbox', '/features/174/bbox', '/features/175/bbox', '/features/176/bbox', '/features/177/bbox', '/features/178/bbox', '/features/179/bbox', '/bbox'], 'feature': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 179]}}
2024-10-05_00:54:25.135 | Fixed geometries for criteria ['unclosed', 'exterior_not_ccw', 'interior_not_cw', 'duplicate_nodes']

ValueError: All arrays must be of the same length

In [ ]:

# Function to convert geometry to text
def geometry_to_text(geom):
    coords = list(geom.exterior.coords) if geom.geom_type == 'Polygon' else list(geom.coords)
    return str([[lon, lat] for lon, lat in coords])

#fixed_geo = fixed_geo.explode(index_parts=True)

# Apply the function to create a new column
fixed_geo['polygons'] = fixed_geo['geometry'].apply(geometry_to_text)

fixed_geo.drop('geometry', axis=1).to_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\IDS-DRR-Assam\Dashboards\risk-score\rc_polygons.csv')

In [10]:
gdf

            revenue_ci district_3  object_id district_1       revenue_cr  \
0   0  Gossaigaon (Pt)  KOKRAJHAR        101  Kokrajhar  Gossaigaon (Pt)
1   0       Bhowraguri  KOKRAJHAR        102  Kokrajhar       Bhawraguri
2   0           Dotoma  KOKRAJHAR        103  Kokrajhar           Dotoma
3   0   Kokrajhar (Pt)  KOKRAJHAR        104  Kokrajhar   Kokrajhar (Pt)
4   0   Bagribari (Pt)  KOKRAJHAR        105  Kokrajhar   Bagribari (Pt)
...                ...        ...        ...        ...              ...
177 3     Ujani Majuli     MAJULI        280     Majuli     Ujani Majuli
    4     Ujani Majuli     MAJULI        280     Majuli     Ujani Majuli
    5     Ujani Majuli     MAJULI        280     Majuli     Ujani Majuli
178 0           Majuli     MAJULI        281     Majuli           Majuli
179 0          Phuloni  K.ANGLONG        275  K.ANGLONG          Phuloni

         HQ          area  are_new  \
0   0  None  1.068572e+09     1069
1   0  None  1.588926e+08      159
2   0  None  3.039662e+08      304
3   0     y  9.902467e+08      990
4   0  None  2.810115e+08      281
...     ...           ...      ...
177 3  None  3.221681e+08      322
    4  None  3.221681e+08      322
    5  None  3.221681e+08      322
178 0  None  6.484667e+08      648
179 0  None  3.303172e+09     3303

                                                geometry  \
0   0  POLYGON ((90.14118 26.74010, 90.15342 26.72894...
1   0  POLYGON ((90.09811 26.46455, 90.10012 26.46386...
2   0  POLYGON ((90.19819 26.63409, 90.21635 26.62661...
3   0  POLYGON ((90.33590 26.86280, 90.33610 26.85565...
4   0  POLYGON ((89.99553 26.35026, 89.99717 26.34893...
...                                                  ...
177 3  POLYGON ((94.49506 27.06108, 94.49520 27.06048...
    4  POLYGON ((94.23632 27.02519, 94.24115 27.02868...
    5  POLYGON ((94.54094 27.10319, 94.54006 27.10182...
178 0  POLYGON ((94.56453 27.18172, 94.56755 27.17914...
179 0  POLYGON ((92.88407 26.38783, 92.88894 26.38798...

                                                polygons
0   0  [[90.14118499638634, 26.740096969418488], [90....
1   0  [[90.09810514517767, 26.46454754372437], [90.1...
2   0  [[90.19818770502957, 26.63408838876364], [90.2...
3   0  [[90.33590156529569, 26.86279883942034], [90.3...
4   0  [[89.99552605935335, 26.35026129608414], [89.9...
...                                                  ...
177 3  [[94.49506277417875, 27.06107502194617], [94.4...
    4  [[94.23631868098583, 27.025185113980243], [94....
    5  [[94.54094468635428, 27.10319221185315], [94.5...
178 0  [[94.5645254607658, 27.181721176397435], [94.5...
179 0  [[92.88406903425019, 26.387832021739342], [92....

[185 rows x 10 columns]

## merge on risk score and export for superset

In [3]:
import geopandas as gpd
from shapely.geometry import Polygon
from shapely.ops import unary_union

# Function to fix invalid geometries
def fix_geometry(geom):
    if geom is None:
        return None
    if not geom.is_valid:
        # Attempt to fix using buffer(0)
        geom = geom.buffer(0)
    return geom if geom.is_valid else None

# Check and fix geometries
def clean_geometries(gdf):
    # Check for missing or invalid geometries
    gdf['geometry_fixed'] = gdf['geometry'].apply(fix_geometry)

    # Drop rows with irreparable (None) geometries
    gdf = gdf.dropna(subset=['geometry_fixed'])

    return gdf

def geometry_to_text(geom):
    if geom is None:
        return None
    
    # Handle Polygon and LineString geometries
    if geom.geom_type == 'Polygon':
        coords = list(geom.exterior.coords)
        return str([[lon, lat] for lon, lat in coords])
    
    elif geom.geom_type == 'LineString':
        coords = list(geom.coords)
        return str([[lon, lat] for lon, lat in coords])
    
    # Handle MultiPolygon and MultiLineString geometries
    elif geom.geom_type in ['MultiPolygon', 'MultiLineString']:
        all_coords = []
        for part in geom.geoms:  # Loop through each sub-geometry
            if part.geom_type == 'Polygon':
                coords = list(part.exterior.coords)
            else:
                coords = list(part.coords)
            all_coords.append([[lon, lat] for lon, lat in coords])
        return str(all_coords)
    
    # Catch other geometry types if necessary
    else:
        return None

In [5]:
geo = gpd.read_file(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\Dashboards\risk-score\assam_rc_reduced.geojson')
geo

,revenue_ci,district_3,object_id,district_1,revenue_cr,HQ,area,are_new,geometry
0,Gossaigaon (Pt),KOKRAJHAR,101,Kokrajhar,Gossaigaon (Pt),None,1.068572e+09,1069,"POLYGON ((90.18542 26.64048, 90.19629 26.67040..."
1,Bhowraguri,KOKRAJHAR,102,Kokrajhar,Bhawraguri,None,1.588926e+08,159,"POLYGON ((90.10500 26.33134, 90.11650 26.35670..."
2,Dotoma,KOKRAJHAR,103,Kokrajhar,Dotoma,None,3.039662e+08,304,"POLYGON ((90.20515 26.37123, 90.18616 26.40796..."
3,Kokrajhar (Pt),KOKRAJHAR,104,Kokrajhar,Kokrajhar (Pt),y,9.902467e+08,990,"POLYGON ((90.36157 26.59586, 90.35400 26.60979..."
4,Bagribari (Pt),KOKRAJHAR,105,Kokrajhar,Bagribari (Pt),None,2.810115e+08,281,"POLYGON ((90.10500 26.33134, 90.05091 26.29692..."
...,...,...,...,...,...,...,...,...,...
175,Sapekhati,CHARAIDEO,278,Charaideo,Sapekhati,None,3.943284e+08,394,"POLYGON ((95.10936 27.12364, 95.10772 27.12040..."
176,Sonari,CHARAIDEO,279,Charaideo,Sonari,y,3.845428e+08,385,"POLYGON ((94.95742 27.06354, 94.96116 27.05681..."
177,Ujani Majuli,MAJULI,280,Majuli,Ujani Majuli,None,3.221681e+08,322,"MULTIPOLYGON (((94.22459 27.03514, 94.22794 27..."
178,Majuli,MAJULI,281,Majuli,Majuli,None,6.484667e+08,648,"POLYGON ((94.56755 27.17914, 94.56373 27.18232..."
179,Phuloni,K.ANGLONG,275,K.ANGLONG,Phuloni,None,3.303172e+09,3303,"POLYGON ((92.94167 26.40076, 92.89326 26.38639..."

In [6]:
fixed_geo = geojson_validator.fix_geometries(geo)#, optional=["duplicate_nodes"])

2024-10-22_10:48:09.270 | Criteria 'optional': ['duplicate_nodes']
2024-10-22_10:48:09.271 | Criteria 'invalid': ['unclosed', 'exterior_not_ccw', 'interior_not_cw']
2024-10-22_10:48:09.272 | Criteria 'problematic': ['duplicate_nodes']
2024-10-22_10:48:09.386 | Null geometry found in GeoJSON Feature, skipping.
2024-10-22_10:48:09.392 | Validation results: {'invalid': {}, 'problematic': {}, 'count_geometry_types': {'Polygon': 178, 'MultiPolygon': 1}, 'skipped_validation': [141]}
2024-10-22_10:48:09.428 | Structure validation results: {'"coordinates" member must be an array, but is a tuple instead': {'path': ['/features/0/geometry', '/features/1/geometry', '/features/2/geometry', '/features/3/geometry', '/features/4/geometry', '/features/5/geometry', '/features/6/geometry', '/features/7/geometry', '/features/8/geometry', '/features/9/geometry', '/features/10/geometry', '/features/11/geometry', '/features/12/geometry', '/features/13/geometry', '/features/14/geometry', '/features/15/geometry', '/features/16/geometry', '/features/17/geometry', '/features/18/geometry', '/features/19/geometry', '/features/20/geometry', '/features/21/geometry', '/features/22/geometry', '/features/23/geometry', '/features/24/geometry', '/features/25/geometry', '/features/26/geometry', '/features/27/geometry', '/features/28/geometry', '/features/29/geometry', '/features/30/geometry', '/features/31/geometry', '/features/32/geometry', '/features/33/geometry', '/features/34/geometry', '/features/35/geometry', '/features/36/geometry', '/features/37/geometry', '/features/38/geometry', '/features/39/geometry', '/features/40/geometry', '/features/41/geometry', '/features/42/geometry', '/features/43/geometry', '/features/44/geometry', '/features/45/geometry', '/features/46/geometry', '/features/47/geometry', '/features/48/geometry', '/features/49/geometry', '/features/50/geometry', '/features/51/geometry', '/features/52/geometry', '/features/53/geometry', '/features/54/geometry', '/features/55/geometry', '/features/56/geometry', '/features/57/geometry', '/features/58/geometry', '/features/59/geometry', '/features/60/geometry', '/features/61/geometry', '/features/62/geometry', '/features/63/geometry', '/features/64/geometry', '/features/65/geometry', '/features/66/geometry', '/features/67/geometry', '/features/68/geometry', '/features/69/geometry', '/features/70/geometry', '/features/71/geometry', '/features/72/geometry', '/features/73/geometry', '/features/74/geometry', '/features/75/geometry', '/features/76/geometry', '/features/77/geometry', '/features/78/geometry', '/features/79/geometry', '/features/80/geometry', '/features/81/geometry', '/features/82/geometry', '/features/83/geometry', '/features/84/geometry', '/features/85/geometry', '/features/86/geometry', '/features/87/geometry', '/features/88/geometry', '/features/89/geometry', '/features/90/geometry', '/features/91/geometry', '/features/92/geometry', '/features/93/geometry', '/features/94/geometry', '/features/95/geometry', '/features/96/geometry', '/features/97/geometry', '/features/98/geometry', '/features/99/geometry', '/features/100/geometry', '/features/101/geometry', '/features/102/geometry', '/features/103/geometry', '/features/104/geometry', '/features/105/geometry', '/features/106/geometry', '/features/107/geometry', '/features/108/geometry', '/features/109/geometry', '/features/110/geometry', '/features/111/geometry', '/features/112/geometry', '/features/113/geometry', '/features/114/geometry', '/features/115/geometry', '/features/116/geometry', '/features/117/geometry', '/features/118/geometry', '/features/119/geometry', '/features/120/geometry', '/features/121/geometry', '/features/122/geometry', '/features/123/geometry', '/features/124/geometry', '/features/125/geometry', '/features/126/geometry', '/features/127/geometry', '/features/128/geometry', '/features/129/geometry', '/features/130/geometry', '/features/131/geometry', '/features/132/geometry', '/features/133/geometry', '/features/134/geometry', '/features/135/geometry', '/features/136/geometry', '/features/137/geometry', '/features/138/geometry', '/features/139/geometry', '/features/140/geometry', '/features/142/geometry', '/features/143/geometry', '/features/144/geometry', '/features/145/geometry', '/features/146/geometry', '/features/147/geometry', '/features/148/geometry', '/features/149/geometry', '/features/150/geometry', '/features/151/geometry', '/features/152/geometry', '/features/153/geometry', '/features/154/geometry', '/features/155/geometry', '/features/156/geometry', '/features/157/geometry', '/features/158/geometry', '/features/159/geometry', '/features/160/geometry', '/features/161/geometry', '/features/162/geometry', '/features/163/geometry', '/features/164/geometry', '/features/165/geometry', '/features/166/geometry', '/features/167/geometry', '/features/168/geometry', '/features/169/geometry', '/features/170/geometry', '/features/171/geometry', '/features/172/geometry', '/features/173/geometry', '/features/174/geometry', '/features/175/geometry', '/features/176/geometry', '/features/178/geometry', '/features/179/geometry'], 'feature': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 178, 179]}, "'bbox' member must be a one-dimensional array with bounding box coordinates": {'path': ['/features/0/bbox', '/features/1/bbox', '/features/2/bbox', '/features/3/bbox', '/features/4/bbox', '/features/5/bbox', '/features/6/bbox', '/features/7/bbox', '/features/8/bbox', '/features/9/bbox', '/features/10/bbox', '/features/11/bbox', '/features/12/bbox', '/features/13/bbox', '/features/14/bbox', '/features/15/bbox', '/features/16/bbox', '/features/17/bbox', '/features/18/bbox', '/features/19/bbox', '/features/20/bbox', '/features/21/bbox', '/features/22/bbox', '/features/23/bbox', '/features/24/bbox', '/features/25/bbox', '/features/26/bbox', '/features/27/bbox', '/features/28/bbox', '/features/29/bbox', '/features/30/bbox', '/features/31/bbox', '/features/32/bbox', '/features/33/bbox', '/features/34/bbox', '/features/35/bbox', '/features/36/bbox', '/features/37/bbox', '/features/38/bbox', '/features/39/bbox', '/features/40/bbox', '/features/41/bbox', '/features/42/bbox', '/features/43/bbox', '/features/44/bbox', '/features/45/bbox', '/features/46/bbox', '/features/47/bbox', '/features/48/bbox', '/features/49/bbox', '/features/50/bbox', '/features/51/bbox', '/features/52/bbox', '/features/53/bbox', '/features/54/bbox', '/features/55/bbox', '/features/56/bbox', '/features/57/bbox', '/features/58/bbox', '/features/59/bbox', '/features/60/bbox', '/features/61/bbox', '/features/62/bbox', '/features/63/bbox', '/features/64/bbox', '/features/65/bbox', '/features/66/bbox', '/features/67/bbox', '/features/68/bbox', '/features/69/bbox', '/features/70/bbox', '/features/71/bbox', '/features/72/bbox', '/features/73/bbox', '/features/74/bbox', '/features/75/bbox', '/features/76/bbox', '/features/77/bbox', '/features/78/bbox', '/features/79/bbox', '/features/80/bbox', '/features/81/bbox', '/features/82/bbox', '/features/83/bbox', '/features/84/bbox', '/features/85/bbox', '/features/86/bbox', '/features/87/bbox', '/features/88/bbox', '/features/89/bbox', '/features/90/bbox', '/features/91/bbox', '/features/92/bbox', '/features/93/bbox', '/features/94/bbox', '/features/95/bbox', '/features/96/bbox', '/features/97/bbox', '/features/98/bbox', '/features/99/bbox', '/features/100/bbox', '/features/101/bbox', '/features/102/bbox', '/features/103/bbox', '/features/104/bbox', '/features/105/bbox', '/features/106/bbox', '/features/107/bbox', '/features/108/bbox', '/features/109/bbox', '/features/110/bbox', '/features/111/bbox', '/features/112/bbox', '/features/113/bbox', '/features/114/bbox', '/features/115/bbox', '/features/116/bbox', '/features/117/bbox', '/features/118/bbox', '/features/119/bbox', '/features/120/bbox', '/features/121/bbox', '/features/122/bbox', '/features/123/bbox', '/features/124/bbox', '/features/125/bbox', '/features/126/bbox', '/features/127/bbox', '/features/128/bbox', '/features/129/bbox', '/features/130/bbox', '/features/131/bbox', '/features/132/bbox', '/features/133/bbox', '/features/134/bbox', '/features/135/bbox', '/features/136/bbox', '/features/137/bbox', '/features/138/bbox', '/features/139/bbox', '/features/140/bbox', '/features/142/bbox', '/features/143/bbox', '/features/144/bbox', '/features/145/bbox', '/features/146/bbox', '/features/147/bbox', '/features/148/bbox', '/features/149/bbox', '/features/150/bbox', '/features/151/bbox', '/features/152/bbox', '/features/153/bbox', '/features/154/bbox', '/features/155/bbox', '/features/156/bbox', '/features/157/bbox', '/features/158/bbox', '/features/159/bbox', '/features/160/bbox', '/features/161/bbox', '/features/162/bbox', '/features/163/bbox', '/features/164/bbox', '/features/165/bbox', '/features/166/bbox', '/features/167/bbox', '/features/168/bbox', '/features/169/bbox', '/features/170/bbox', '/features/171/bbox', '/features/172/bbox', '/features/173/bbox', '/features/174/bbox', '/features/175/bbox', '/features/176/bbox', '/features/177/bbox', '/features/178/bbox', '/features/179/bbox', '/bbox'], 'feature': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 179]}, "Array is not deep enough nested, expected depth 4 for type 'MultiPolygon', found depth 1": {'path': ['/features/177/geometry/coordinates'], 'feature': [177]}}
2024-10-22_10:48:09.441 | Fixed geometries for criteria ['unclosed', 'exterior_not_ccw', 'interior_not_cw', 'duplicate_nodes']

In [7]:

# Example usage
# Assume `fixed_geo` is your GeoDataFrame

fixed_geo = clean_geometries(geo)

# Apply your geometry_to_text function afterward
fixed_geo['polygons'] = fixed_geo['geometry_fixed'].apply(geometry_to_text)

c:\Users\saura\anaconda3\envs\cdl-env\Lib\site-packages\geopandas\geodataframe.py:1528: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  super().__setitem__(key, value)

In [8]:
fixed_geo

,revenue_ci,district_3,object_id,district_1,revenue_cr,HQ,area,are_new,geometry,geometry_fixed,polygons
0,Gossaigaon (Pt),KOKRAJHAR,101,Kokrajhar,Gossaigaon (Pt),None,1.068572e+09,1069,"POLYGON ((90.18542 26.64048, 90.19629 26.67040...","POLYGON ((90.18542 26.64048, 90.19629 26.67040...","[[90.18541866620383, 26.64047548366383], [90.1..."
1,Bhowraguri,KOKRAJHAR,102,Kokrajhar,Bhawraguri,None,1.588926e+08,159,"POLYGON ((90.10500 26.33134, 90.11650 26.35670...","POLYGON ((90.10500 26.33134, 90.11650 26.35670...","[[90.10500293993516, 26.331344274458672], [90...."
2,Dotoma,KOKRAJHAR,103,Kokrajhar,Dotoma,None,3.039662e+08,304,"POLYGON ((90.20515 26.37123, 90.18616 26.40796...","POLYGON ((90.20515 26.37123, 90.18616 26.40796...","[[90.20515067076427, 26.371233634539827], [90...."
3,Kokrajhar (Pt),KOKRAJHAR,104,Kokrajhar,Kokrajhar (Pt),y,9.902467e+08,990,"POLYGON ((90.36157 26.59586, 90.35400 26.60979...","POLYGON ((90.36157 26.59586, 90.35400 26.60979...","[[90.3615654591892, 26.595861598595977], [90.3..."
4,Bagribari (Pt),KOKRAJHAR,105,Kokrajhar,Bagribari (Pt),None,2.810115e+08,281,"POLYGON ((90.10500 26.33134, 90.05091 26.29692...","POLYGON ((90.10500 26.33134, 90.05091 26.29692...","[[90.10500293993516, 26.331344274458672], [90...."
...,...,...,...,...,...,...,...,...,...,...,...
175,Sapekhati,CHARAIDEO,278,Charaideo,Sapekhati,None,3.943284e+08,394,"POLYGON ((95.10936 27.12364, 95.10772 27.12040...","POLYGON ((95.10936 27.12364, 95.10772 27.12040...","[[95.10935789278463, 27.12363873037319], [95.1..."
176,Sonari,CHARAIDEO,279,Charaideo,Sonari,y,3.845428e+08,385,"POLYGON ((94.95742 27.06354, 94.96116 27.05681...","POLYGON ((94.95742 27.06354, 94.96116 27.05681...","[[94.95741744211, 27.063543620157468], [94.961..."
177,Ujani Majuli,MAJULI,280,Majuli,Ujani Majuli,None,3.221681e+08,322,"MULTIPOLYGON (((94.22459 27.03514, 94.22794 27...","MULTIPOLYGON (((94.22459 27.03514, 94.22794 27...","[[[94.22459130700403, 27.035135395665876], [94..."
178,Majuli,MAJULI,281,Majuli,Majuli,None,6.484667e+08,648,"POLYGON ((94.56755 27.17914, 94.56373 27.18232...","POLYGON ((94.56755 27.17914, 94.56373 27.18232...","[[94.56755479460118, 27.179143785122843], [94...."
179,Phuloni,K.ANGLONG,275,K.ANGLONG,Phuloni,None,3.303172e+09,3303,"POLYGON ((92.94167 26.40076, 92.89326 26.38639...","POLYGON ((92.94167 26.40076, 92.89326 26.38639...","[[92.94167314970476, 26.400758104242115], [92...."

In [9]:

# Apply the function to create a new column
#geo['polygons'] = geo['geometry'].apply(geometry_to_text)
polygons = fixed_geo.drop(['geometry_fixed','geometry'], axis=1)

In [10]:
risk_score = pd.read_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\IDS-DRR-Assam\RiskScoreModel\data\risk_score_final_district.csv')
risk_score

C:\Users\saura\AppData\Local\Temp\ipykernel_29416\3964797053.py:1: DtypeWarning: Columns (28,29,30,31,32,68,69) have mixed types. Specify dtype option on import or set low_memory=False.
  risk_score = pd.read_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\IDS-DRR-Assam\RiskScoreModel\data\risk_score_final_district.csv')

,object-id,district,rc-area,timeperiod,total-tender-awarded-value,sopd-tenders-awarded-value,sdrf-sanctions-awarded-value,sdrf-tenders-awarded-value,ridf-tenders-awarded-value,ltif-tenders-awarded-value,...,total-hhd,distance-from-river,drainage-density,exposure,flood-hazard,government-response,vulnerability,efficiency,topsis-score,risk-score
0,257,SOUTH SALMARA MANCACHAR,249.0,2021_04,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,151388.0,1193.338972,0.000541,4,3.0,2,4,0.887027,0.875140,5
1,185,CACHAR,838.0,2021_04,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,181388.0,3479.873117,0.000509,5,2.0,2,4,0.874512,0.597299,4
2,121,BARPETA,513.0,2021_04,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,76764.0,458.191524,0.000640,3,2.0,2,5,0.834827,0.585299,4
3,266,BARPETA,318.0,2021_04,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,70052.0,846.076906,0.000613,2,2.0,2,5,0.841075,0.559509,4
4,200,BONGAIGAON,348.0,2021_04,0.000000e+00,0.0,0.0,0.0,0.0,0.0,...,59943.0,1931.695231,0.000611,2,2.0,2,5,0.834087,0.559509,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9025,14,WEST KARBI ANGLONG,NaN,2024_05,6.091080e+07,0.0,0.0,0.0,60910798.0,0.0,...,52339.0,4989.532823,0.000439,3,1.0,1,2,0.956387,NaN,1
9026,14,WEST KARBI ANGLONG,NaN,2024_06,6.091080e+07,0.0,0.0,0.0,60910798.0,0.0,...,52339.0,4989.532823,0.000439,3,1.0,1,1,0.982300,NaN,1
9027,14,WEST KARBI ANGLONG,NaN,2024_07,6.091080e+07,0.0,0.0,0.0,60910798.0,0.0,...,52339.0,4989.532823,0.000439,3,1.0,5,4,0.748095,NaN,2
9028,14,WEST KARBI ANGLONG,NaN,2024_08,1.258670e+08,0.0,0.0,0.0,125867046.0,0.0,...,52339.0,4989.532823,0.000439,3,1.0,1,2,0.956387,NaN,1
9029,14,WEST KARBI ANGLONG,NaN,2024_09,1.552178e+08,0.0,0.0,0.0,125867046.0,0.0,...,52339.0,4989.532823,0.000439,3,1.0,1,2,0.956387,NaN,1

In [11]:
merged = risk_score.merge(polygons, left_on='object-id',right_on='object_id')
merged

,object-id,district,rc-area,timeperiod,total-tender-awarded-value,sopd-tenders-awarded-value,sdrf-sanctions-awarded-value,sdrf-tenders-awarded-value,ridf-tenders-awarded-value,ltif-tenders-awarded-value,...,risk-score,revenue_ci,district_3,object_id,district_1,revenue_cr,HQ,area_y,are_new,polygons
0,257,SOUTH SALMARA MANCACHAR,249.0,2021_04,0.000000e+00,0.00,0.0,0.0,0.0,0.0,...,5,Mankachar,SOUTH SALMARA MANCACHAR,257,South Salmara Mancachar,Mankachar,None,2.486782e+08,249,"[[89.94335289669684, 25.757424190107606], [89...."
1,185,CACHAR,838.0,2021_04,0.000000e+00,0.00,0.0,0.0,0.0,0.0,...,4,Silchar,CACHAR,185,Cachar,Silchar,y,8.379318e+08,838,"[[92.85688937884176, 25.064839571262386], [92...."
2,121,BARPETA,513.0,2021_04,0.000000e+00,0.00,0.0,0.0,0.0,0.0,...,4,Baghbor,BARPETA,121,Barpeta,Baghbor,None,5.128307e+08,513,"[[91.01785504944317, 26.224337303887015], [91...."
3,266,BARPETA,318.0,2021_04,0.000000e+00,0.00,0.0,0.0,0.0,0.0,...,4,Chenga,BARPETA,266,Barpeta,Chenga,None,3.175222e+08,318,"[[91.01785504944317, 26.224337303887015], [91...."
4,200,BONGAIGAON,348.0,2021_04,0.000000e+00,0.00,0.0,0.0,0.0,0.0,...,4,Srijangram,BONGAIGAON,200,Bongaigaon,Srijangram,None,3.475838e+08,348,"[[90.84496410408536, 26.403304597629205], [90...."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7513,239,DARRANG,293.0,2024_09,1.793006e+08,0.00,0.0,0.0,179300633.0,0.0,...,1,Sipajhar,DARRANG,239,Darrang,Sipajhar,None,2.930072e+08,293,"[[91.94166610236094, 26.247998080667802], [91...."
7514,178,K.ANGLONG,2468.0,2024_09,1.548520e+08,0.00,0.0,0.0,98455505.0,0.0,...,1,Diphu,K.ANGLONG,178,Karbi Anglong,Diphu,y,2.467568e+09,2468,"[[93.82160904055343, 26.172295664349594], [93...."
7515,226,NALBARI,128.0,2024_09,3.099482e+08,6998798.91,0.0,0.0,104695778.0,0.0,...,1,Nalbari,NALBARI,226,Nalbari,Nalbari,y,1.281369e+08,128,"[[91.48899948898612, 26.417890516944205], [91...."
7516,124,BAJALI,167.0,2024_09,1.518096e+08,14939735.00,0.0,0.0,136869816.0,0.0,...,1,Bajali (Pt),BAJALI,124,Barpeta,Bajali (Pt),None,1.671295e+08,167,"[[91.23758008704172, 26.59162328689672], [91.2..."
7517,281,MAJULI,648.0,2024_09,9.172079e+08,0.00,0.0,0.0,0.0,0.0,...,1,Majuli,MAJULI,281,Majuli,Majuli,None,6.484667e+08,648,"[[94.56755479460118, 27.179143785122843], [94...."

In [12]:
from datetime import date, timedelta, datetime


#snapshot_ld_dist['datetime'] = pd.to_datetime(snapshot_ld_dist['timeperiod'], format='%Y_%m')
merged['timeperiod_iso'] = merged['timeperiod'].str.replace('_', '-') #+ '-01'

# Step 2: Convert the modified column to datetime format
#snapshot_ld_dist['timeperiod_iso'] = pd.to_datetime(snapshot_ld_dist['timeperiod_iso'], format='%Y-%m-%d')
merged['timeperiod_iso'] = pd.to_datetime(merged['timeperiod_iso'], format='%Y-%m')


merged['timeperiod_iso'] = merged['timeperiod_iso'].dt.strftime('%Y-%m')

In [14]:
merged.to_csv(r'D:\CivicDataLab_IDS-DRR\IDS-DRR_Github\Dashboards\risk-score\risk_score_polygons.csv')